### ISSUE TITLE
video props, autoplay, muted

### ISSUE THREAD

**Issue by edwinlimlx** [brightcove/react-player-loader#57]
I want to embed the player with a background video, which i'm able to setup successfully, however can't seems to pass any props to the video element. props such as muted, autoplay and loop.

**Comment by misteroneill** [comment]
You can pass any Video.js options you want via the `options` prop, which [comes from the base player-loader](https://github.com/brightcove/player-loader#options) project.

Something like this should work (inside a component render function):

```
const options = {
  autoplay: true,
  loop: true,
  muted: true
};

return <ReactPlayerLoader accountId='1234678' videoId='87654321' options={options} />;
```

**Comment by ekeyur** [comment]
@misteroneill : The above options sure do work on desktop. The autoplay functionality does not work on mobile. Is this intentional? Is it possible to bypass?

**Comment by misteroneill** [comment]
Kinda.

Autoplay is severely limited on mobile for many (good) reasons (UX and bandwidth chief among them). For one, the `playsinline` attribute (can be passed as an option as above) is required on iOS. Otherwise, I believe (not 100% sure in all cases) that `muted` is generally required.

Here's [a blog post](https://blog.videojs.com/autoplay-best-practices-with-video-js/) on the topic. It's a bit old, but mostly still holds true.

If by "bypass" you mean circumvent the browsers'/user's built-in autoplay behaviors: no, there is no way to do that.

**Comment by ArtixZ** [comment]
Where should I turn controls off. `controls: false` doesn't work.
