### ISSUE TITLE
Failed to minify on build

### ISSUE THREAD

**Issue by Mantis748** [brightcove/react-player-loader#8]
Bootstrapped a project in Visual Studio Code using create-react-app, then installed @brightcove/react-player-loader. The dependency works fine during development, but when building (npm run build at the terminal), the following message is received:

> 

> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file:
>         ./node_modules/@brightcove/react-player-loader/dist/brightcove-react-player-loader.es.js:251
> 
> Read more here: http://bit.ly/2tRViJ9

>
I'm new at JS dev, but from what I gather in the link above, this was published as an ES6 file and needs to be built and published as a transpiled version.

**Comment by gkatsev** [comment]
Thanks for the issue. Looks like we are transforming the files but there is some ES6 code left like const. We are using the browserlist project to determine which browsers to target and it's possible that they all support things like `const`. The minifier that is being used probably doesn't support `const` and thus the build fails. Looking at create-react-app, it looks like it's using webpack 3, which uses uglifyjs-webpack-plugin 0.4.6, which uses uglify 2, which doesn't support *any* ES6 features.
We'll investigate what we can do for this.

**Comment by misteroneill** [comment]
It seems like this issue is specific to this project - or specific to modules that are `import`ed.

- player-loader is transpiled in its various dist files. For example, [here](https://unpkg.com/@brightcove/player-loader@1.3.1/dist/brightcove-player-loader.es.js).
- player-loader specifies that linked file in the `module` field, [here](https://github.com/brightcove/player-loader/blob/master/package.json#L6).
- However, when [`import` player-loader](https://github.com/brightcove/react-player-loader/blob/master/src/index.js#L2) in this project, somehow we end up with its [un-transpiled source code](https://unpkg.com/@brightcove/react-player-loader@1.0.1/dist/brightcove-react-player-loader.es.js) (search for `const DEFAULTS`).

I am still trying to figure out _why_ this is the case.

**Comment by misteroneill** [comment]
@Mantis748 Please try again with 1.0.2 of this library. Hope it resolves your issue. If not, please let us know.

**Comment by misteroneill** [comment]
No worries - thanks for reporting the issue @Mantis748 - it's really appreciated!
